from flask import Flask, request
from flask_cors import CORS
from openai import OpenAI

app = Flask(__name__)
CORS(app)

@app.route('/hello')
def hello():
    # Get the prompt string from the query parameters
    prompt = request.args.get('prompt', '')
    print("HELLO", prompt)
    # Create an instance of the OpenAI client with your API key
    client = OpenAI(api_key="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")

    # Generate a completion using the GPT-3.5 model
    completion = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}   # Use the provided prompt as the user's message
        ]
    )

    # Return the response generated by the AI model
    return completion.choices[0].message.content

if __name__ == '__main__':
    app.run(debug=True)
